spring.application.name=simple-auth-app

# =========================================
# APPLICATION
# =========================================

# =========================================
# H2 DATABASE
# =========================================
spring.datasource.url=jdbc:h2:mem:gestion_employes_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# =========================================
# HIBERNATE / JPA
# =========================================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================
# H2 CONSOLE
# =========================================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# =========================================
# LOGGING
# =========================================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# =========================================
# SECURITY
# =========================================
jwt.secret = jwt.secret = kJ9sL8xQ2mN7vT4pR1zY6wE3uI5oA8dF0gH7jK2lM9nP4qR6sT1vW3xZ5cB8eD2f
jwt.expiration = 86000000

